import mods.mfr.MiningLaser;

print("SCRIPT: MFR Laser Drill");

MiningLaser.removeOre(<ThermalFoundation:Ore>);
MiningLaser.removeOre(<ThermalFoundation:Ore:6>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:3>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:12>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:4>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:9>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:12>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:6>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:10>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:11>);
MiningLaser.removeOre(<ThermalFoundation:Ore:1>);
MiningLaser.removeOre(<appliedenergistics2:tile.OreQuartz>);
MiningLaser.removeOre(<BigReactors:YelloriteOre>);
MiningLaser.removeOre(<Metallurgy:base.ore:2>);
MiningLaser.removeOre(<Metallurgy:ender.ore:1>);
MiningLaser.removeOre(<Metallurgy:ender.ore>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:1>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:11>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:14>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:2>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:4>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:5>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:6>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore:8>);
MiningLaser.removeOre(<Metallurgy:fantasy.ore>);
MiningLaser.removeOre(<Metallurgy:nether.ore:1>);
MiningLaser.removeOre(<Metallurgy:nether.ore:2>);
MiningLaser.removeOre(<Metallurgy:nether.ore:3>);
MiningLaser.removeOre(<Metallurgy:nether.ore:4>);
MiningLaser.removeOre(<Metallurgy:nether.ore:5>);
MiningLaser.removeOre(<Metallurgy:nether.ore:6>);
MiningLaser.removeOre(<Metallurgy:nether.ore:7>);
MiningLaser.removeOre(<Metallurgy:nether.ore:8>);
MiningLaser.removeOre(<Metallurgy:nether.ore:9>);
MiningLaser.removeOre(<Metallurgy:nether.ore>);
MiningLaser.removeOre(<Metallurgy:precious.ore>);
MiningLaser.removeOre(<Metallurgy:utility.ore:1>);
MiningLaser.removeOre(<Metallurgy:utility.ore:2>);
MiningLaser.removeOre(<Metallurgy:utility.ore:3>);
MiningLaser.removeOre(<Metallurgy:utility.ore:4>);
MiningLaser.removeOre(<Metallurgy:utility.ore:5>);
MiningLaser.removeOre(<Metallurgy:utility.ore>);
MiningLaser.removeOre(<minecraft:coal_ore>);
MiningLaser.removeOre(<minecraft:diamond_ore>);
MiningLaser.removeOre(<minecraft:emerald_ore>);
MiningLaser.removeOre(<minecraft:glowstone>);
MiningLaser.removeOre(<minecraft:gold_ore>);
MiningLaser.removeOre(<minecraft:iron_ore>);
MiningLaser.removeOre(<minecraft:lapis_ore>);
MiningLaser.removeOre(<minecraft:quartz_ore>);
MiningLaser.removeOre(<minecraft:redstone_ore>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:1>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:10>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:13>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:14>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:15>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:2>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:3>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:4>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:5>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:6>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:7>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:8>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0:9>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.0>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:1>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:11>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:13>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:14>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:15>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:2>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:5>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:7>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1:8>);
MiningLaser.removeOre(<NetherOres:tile.netherores.ore.1>);
MiningLaser.removeOre(<TConstruct:SearedBrick:1>);
MiningLaser.removeOre(<TConstruct:SearedBrick:2>);
MiningLaser.removeOre(<TConstruct:SearedBrick:5>);
MiningLaser.removeOre(<Thaumcraft:blockCustomOre:7>);
MiningLaser.removeOre(<Thaumcraft:blockCustomOre>);
MiningLaser.removeOre(<ThermalFoundation:Ore:2>);
MiningLaser.removeOre(<ThermalFoundation:Ore:3>);
MiningLaser.removeOre(<ThermalFoundation:Ore:4>);
MiningLaser.removeOre(<ThermalFoundation:Ore:5>);

MiningLaser.addOre(<appliedenergistics2:tile.OreQuartz>.weight(40));
MiningLaser.addOre(<BigReactors:YelloriteOre>.weight(5));
MiningLaser.addOre(<Metallurgy:base.ore:2>.weight(20));
MiningLaser.addOre(<Metallurgy:ender.ore:1>.weight(15));
MiningLaser.addOre(<Metallurgy:ender.ore>.weight(8));
MiningLaser.addOre(<Metallurgy:fantasy.ore:1>.weight(55));
MiningLaser.addOre(<Metallurgy:fantasy.ore:11>.weight(20));
MiningLaser.addOre(<Metallurgy:fantasy.ore:14>.weight(10));
MiningLaser.addOre(<Metallurgy:fantasy.ore:2>.weight(50));
MiningLaser.addOre(<Metallurgy:fantasy.ore:4>.weight(45));
MiningLaser.addOre(<Metallurgy:fantasy.ore:5>.weight(40));
MiningLaser.addOre(<Metallurgy:fantasy.ore:6>.weight(35));
MiningLaser.addOre(<Metallurgy:fantasy.ore:8>.weight(25));
MiningLaser.addOre(<Metallurgy:fantasy.ore>.weight(50));
MiningLaser.addOre(<Metallurgy:nether.ore:1>.weight(24));
MiningLaser.addOre(<Metallurgy:nether.ore:2>.weight(20));
MiningLaser.addOre(<Metallurgy:nether.ore:3>.weight(17));
MiningLaser.addOre(<Metallurgy:nether.ore:4>.weight(16));
MiningLaser.addOre(<Metallurgy:nether.ore:5>.weight(14));
MiningLaser.addOre(<Metallurgy:nether.ore:6>.weight(12));
MiningLaser.addOre(<Metallurgy:nether.ore:7>.weight(10));
MiningLaser.addOre(<Metallurgy:nether.ore:8>.weight(9));
MiningLaser.addOre(<Metallurgy:nether.ore:9>.weight(8));
MiningLaser.addOre(<Metallurgy:nether.ore>.weight(28));
MiningLaser.addOre(<Metallurgy:precious.ore>.weight(40));
MiningLaser.addOre(<Metallurgy:utility.ore:1>.weight(20));
MiningLaser.addOre(<Metallurgy:utility.ore:2>.weight(35));
MiningLaser.addOre(<Metallurgy:utility.ore:3>.weight(25));
MiningLaser.addOre(<Metallurgy:utility.ore:4>.weight(35));
MiningLaser.addOre(<Metallurgy:utility.ore:5>.weight(20));
MiningLaser.addOre(<Metallurgy:utility.ore>.weight(35));
MiningLaser.addOre(<minecraft:coal_ore>.weight(150));
MiningLaser.addOre(<minecraft:diamond_ore>.weight(50));
MiningLaser.addOre(<minecraft:emerald_ore>.weight(35));
MiningLaser.addOre(<minecraft:glowstone>.weight(65));
MiningLaser.addOre(<minecraft:gold_ore>.weight(70));
MiningLaser.addOre(<minecraft:iron_ore>.weight(130));
MiningLaser.addOre(<minecraft:lapis_ore>.weight(80));
MiningLaser.addOre(<minecraft:quartz_ore>.weight(70));
MiningLaser.addOre(<minecraft:redstone_ore>.weight(90));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:1>.weight(10));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:10>.weight(6));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:13>.weight(10));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:14>.weight(10));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:15>.weight(10));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:2>.weight(14));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:3>.weight(26));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:4>.weight(16));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:5>.weight(18));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:6>.weight(8));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:7>.weight(7));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:8>.weight(7));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0:9>.weight(5));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.0>.weight(30));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:1>.weight(4));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:11>.weight(15));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:13>.weight(15));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:14>.weight(20));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:15>.weight(12));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:2>.weight(10));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:5>.weight(20));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:7>.weight(6));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1:8>.weight(3));
MiningLaser.addOre(<NetherOres:tile.netherores.ore.1>.weight(3));
MiningLaser.addOre(<TConstruct:SearedBrick:1>.weight(10));
MiningLaser.addOre(<TConstruct:SearedBrick:2>.weight(12));
MiningLaser.addOre(<TConstruct:SearedBrick:5>.weight(60));
MiningLaser.addOre(<Thaumcraft:blockCustomOre:7>.weight(75));
MiningLaser.addOre(<Thaumcraft:blockCustomOre>.weight(65));
MiningLaser.addOre(<ThermalFoundation:Ore:3>.weight(30));
MiningLaser.addOre(<ThermalFoundation:Ore:4>.weight(20));
MiningLaser.addOre(<Metallurgy:base.ore:1>.weight(35));
MiningLaser.addOre(<Metallurgy:base.ore:0>.weight(40));
MiningLaser.addOre(<Metallurgy:precious.ore:1>.weight(25));
MiningLaser.addOre(<Metallurgy:precious.ore:2>.weight(15));
MiningLaser.addOre(<harvestcraft:salt>.weight(75));
MiningLaser.addOre(<Thaumcraft:blockCustomOre:1>.weight(5));
MiningLaser.addOre(<Thaumcraft:blockCustomOre:4>.weight(40));
MiningLaser.addOre(<Thaumcraft:blockCustomOre:2>.weight(40));
MiningLaser.addOre(<Thaumcraft:blockCustomOre:3>.weight(20));
MiningLaser.addOre(<Thaumcraft:blockCustomOre:5>.weight(30));
MiningLaser.addOre(<Thaumcraft:blockCustomOre:6>.weight(10));
MiningLaser.addOre(<Metallurgy:fantasy.ore:13>.weight(15));
MiningLaser.addOre(<Metallurgy:fantasy.ore:7>.weight(30));
MiningLaser.addOre(<minecraft:fish>.weight(1));

MiningLaser.removePreferredOre(0, <NetherOres:tile.netherores.ore.1:13> );
MiningLaser.removePreferredOre(0, <minecraft:quartz_ore> );
MiningLaser.removePreferredOre(0, <Metallurgy:precious.ore> );
MiningLaser.removePreferredOre(0, <TConstruct:SearedBrick:5> );
MiningLaser.removePreferredOre(0, <Metallurgy:utility.ore:2> );
MiningLaser.removePreferredOre(0, <NetherOres:tile.netherores.ore.1:14> );
MiningLaser.removePreferredOre(0, <NetherOres:tile.netherores.ore.1:3> );
MiningLaser.removePreferredOre(1, <ThermalFoundation:Ore> );
MiningLaser.removePreferredOre(1, <NetherOres:tile.netherores.ore.0:6> );
MiningLaser.removePreferredOre(1, <Thaumcraft:blockCustomOre:7> );
MiningLaser.removePreferredOre(1, <NetherOres:tile.netherores.ore.1:11> );
MiningLaser.removePreferredOre(1, <TConstruct:SearedBrick:2> );
MiningLaser.removePreferredOre(3, <NetherOres:tile.netherores.ore.0:12> );
MiningLaser.removePreferredOre(3, <minecraft:diamond_ore> );
MiningLaser.removePreferredOre(3, <NetherOres:tile.netherores.ore.0:1> );
MiningLaser.removePreferredOre(3, <NetherOres:tile.netherores.ore.1:4> );
MiningLaser.removePreferredOre(3, <ThermalFoundation:Ore:5> );
MiningLaser.removePreferredOre(3, <NetherOres:tile.netherores.ore.1> );
MiningLaser.removePreferredOre(4, <minecraft:glowstone> );
MiningLaser.removePreferredOre(4, <minecraft:gold_ore> );
MiningLaser.removePreferredOre(4, <NetherOres:tile.netherores.ore.0:2> );
MiningLaser.removePreferredOre(4, <Metallurgy:utility.ore> );
MiningLaser.removePreferredOre(4, <NetherOres:tile.netherores.ore.1:5> );
MiningLaser.removePreferredOre(4, <BigReactors:YelloriteOre> );
MiningLaser.removePreferredOre(5, <NetherOres:tile.netherores.ore.1:12> );
MiningLaser.removePreferredOre(5, <minecraft:emerald_ore> );
MiningLaser.removePreferredOre(5, <NetherOres:tile.netherores.ore.0:8> );
MiningLaser.removePreferredOre(5, <NetherOres:tile.netherores.ore.0:11> );
MiningLaser.removePreferredOre(6, <Metallurgy:base.ore:2> );
MiningLaser.removePreferredOre(6, <Metallurgy:ender.ore:1> );
MiningLaser.removePreferredOre(6, <Metallurgy:ender.ore> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:14> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:11> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:8> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:6> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:5> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:4> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:2> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore:1> );
MiningLaser.removePreferredOre(6, <Metallurgy:fantasy.ore> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:9> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:8> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:7> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:6> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:5> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:4> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:3> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:2> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore:1> );
MiningLaser.removePreferredOre(6, <Metallurgy:nether.ore> );
MiningLaser.removePreferredOre(6, <Metallurgy:utility.ore:5> );
MiningLaser.removePreferredOre(6, <Metallurgy:utility.ore:4> );
MiningLaser.removePreferredOre(6, <Metallurgy:utility.ore:1> );
MiningLaser.removePreferredOre(7, <NetherOres:tile.netherores.ore.1:2> );
MiningLaser.removePreferredOre(7, <ThermalFoundation:Ore:2> );
MiningLaser.removePreferredOre(7, <NetherOres:tile.netherores.ore.0:9> );
MiningLaser.removePreferredOre(8, <ThermalFoundation:Ore:1> );
MiningLaser.removePreferredOre(8, <NetherOres:tile.netherores.ore.0:7> );
MiningLaser.removePreferredOre(8, <ThermalFoundation:Ore:4> );
MiningLaser.removePreferredOre(8, <NetherOres:tile.netherores.ore.1:1> );
MiningLaser.removePreferredOre(8, <Metallurgy:utility.ore:3> );
MiningLaser.removePreferredOre(8, <NetherOres:tile.netherores.ore.1:15> );
MiningLaser.removePreferredOre(9, <appliedenergistics2:tile.OreQuartz> );
MiningLaser.removePreferredOre(10, <ThermalFoundation:Ore:3> );
MiningLaser.removePreferredOre(10, <NetherOres:tile.netherores.ore.0:10> );
MiningLaser.removePreferredOre(11, <minecraft:lapis_ore> );
MiningLaser.removePreferredOre(11, <NetherOres:tile.netherores.ore.0:4> );
MiningLaser.removePreferredOre(11, <ThermalFoundation:Ore:6> );
MiningLaser.removePreferredOre(11, <NetherOres:tile.netherores.ore.1:7> );
MiningLaser.removePreferredOre(11, <NetherOres:tile.netherores.ore.0:15> );
MiningLaser.removePreferredOre(11, <TConstruct:SearedBrick:1> );
MiningLaser.removePreferredOre(12, <minecraft:iron_ore> );
MiningLaser.removePreferredOre(12, <NetherOres:tile.netherores.ore.0:3> );
MiningLaser.removePreferredOre(13, <NetherOres:tile.netherores.ore.0:14> );
MiningLaser.removePreferredOre(13, <NetherOres:tile.netherores.ore.1:8> );
MiningLaser.removePreferredOre(14, <minecraft:redstone_ore> );
MiningLaser.removePreferredOre(14, <NetherOres:tile.netherores.ore.0:5> );
MiningLaser.removePreferredOre(14, <NetherOres:tile.netherores.ore.0:13> );
MiningLaser.removePreferredOre(14, <Thaumcraft:blockCustomOre> );
MiningLaser.removePreferredOre(15, <minecraft:coal_ore> );
MiningLaser.removePreferredOre(15, <NetherOres:tile.netherores.ore.0> );
MiningLaser.removePreferredOre(15, <NetherOres:tile.netherores.ore.1:9> );
MiningLaser.removePreferredOre(15, <NetherOres:tile.netherores.ore.1:6> );
MiningLaser.removePreferredOre(15, <NetherOres:tile.netherores.ore.1:10> );

MiningLaser.addPreferredOre(4, <BigReactors:YelloriteOre>);
MiningLaser.addPreferredOre(1, <Metallurgy:base.ore:2>);
MiningLaser.addPreferredOre(15, <Metallurgy:ender.ore:1>);
MiningLaser.addPreferredOre(15, <Metallurgy:ender.ore>);
MiningLaser.addPreferredOre(7, <Metallurgy:fantasy.ore:1>);
MiningLaser.addPreferredOre(2, <Metallurgy:fantasy.ore:11>);
MiningLaser.addPreferredOre(2, <Metallurgy:fantasy.ore:14>);
MiningLaser.addPreferredOre(12, <Metallurgy:fantasy.ore:2>);
MiningLaser.addPreferredOre(12, <Metallurgy:fantasy.ore:4>);
MiningLaser.addPreferredOre(12, <Metallurgy:fantasy.ore:5>);
MiningLaser.addPreferredOre(2, <Metallurgy:fantasy.ore:6>);
MiningLaser.addPreferredOre(12, <Metallurgy:fantasy.ore:8>);
MiningLaser.addPreferredOre(12, <Metallurgy:fantasy.ore>);
MiningLaser.addPreferredOre(7, <Metallurgy:nether.ore:1>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:2>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:3>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:4>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:5>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:6>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:7>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:8>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore:9>);
MiningLaser.addPreferredOre(6, <Metallurgy:nether.ore>);
MiningLaser.addPreferredOre(1, <Metallurgy:precious.ore>);
MiningLaser.addPreferredOre(1, <Metallurgy:utility.ore:1>);
MiningLaser.addPreferredOre(1, <Metallurgy:utility.ore:2>);
MiningLaser.addPreferredOre(1, <Metallurgy:utility.ore:3>);
MiningLaser.addPreferredOre(1, <Metallurgy:utility.ore:4>);
MiningLaser.addPreferredOre(1, <Metallurgy:utility.ore:5>);
MiningLaser.addPreferredOre(1, <Metallurgy:utility.ore>);
MiningLaser.addPreferredOre(4, <minecraft:coal_ore>);
MiningLaser.addPreferredOre(3, <minecraft:diamond_ore>);
MiningLaser.addPreferredOre(13, <minecraft:emerald_ore>);
MiningLaser.addPreferredOre(6, <minecraft:glowstone>);
MiningLaser.addPreferredOre(7, <minecraft:iron_ore>);
MiningLaser.addPreferredOre(11, <minecraft:lapis_ore>);
MiningLaser.addPreferredOre(0, <minecraft:quartz_ore>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:1>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:10>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:13>);
MiningLaser.addPreferredOre(13, <NetherOres:tile.netherores.ore.0:14>);
MiningLaser.addPreferredOre(11, <NetherOres:tile.netherores.ore.0:15>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:2>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:3>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:4>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:5>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:6>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:7>);
MiningLaser.addPreferredOre(13, <NetherOres:tile.netherores.ore.0:8>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0:9>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.0>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:1>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:11>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:13>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:14>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:15>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:2>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:5>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:7>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1:8>);
MiningLaser.addPreferredOre(14, <NetherOres:tile.netherores.ore.1>);
MiningLaser.addPreferredOre(6, <TConstruct:SearedBrick:1>);
MiningLaser.addPreferredOre(6, <TConstruct:SearedBrick:2>);
MiningLaser.addPreferredOre(8, <TConstruct:SearedBrick:5>);
MiningLaser.addPreferredOre(1, <Thaumcraft:blockCustomOre:7>);
MiningLaser.addPreferredOre(1, <Thaumcraft:blockCustomOre>);
MiningLaser.addPreferredOre(8, <ThermalFoundation:Ore:3>);
MiningLaser.addPreferredOre(8, <ThermalFoundation:Ore:4>);
MiningLaser.addPreferredOre(8, <Metallurgy:base.ore:1>);
MiningLaser.addPreferredOre(8, <Metallurgy:base.ore:0>);
MiningLaser.addPreferredOre(8, <Metallurgy:precious.ore:1>);
MiningLaser.addPreferredOre(8, <Metallurgy:precious.ore:2>);
MiningLaser.addPreferredOre(0, <harvestcraft:salt>);
MiningLaser.addPreferredOre(10, <Thaumcraft:blockCustomOre:1>);
MiningLaser.addPreferredOre(10, <Thaumcraft:blockCustomOre:4>);
MiningLaser.addPreferredOre(10, <Thaumcraft:blockCustomOre:2>);
MiningLaser.addPreferredOre(10, <Thaumcraft:blockCustomOre:3>);
MiningLaser.addPreferredOre(10, <Thaumcraft:blockCustomOre:5>);
MiningLaser.addPreferredOre(10, <Thaumcraft:blockCustomOre:6>);
MiningLaser.addPreferredOre(2, <Metallurgy:fantasy.ore:13>);
MiningLaser.addPreferredOre(2, <Metallurgy:fantasy.ore:7>);
MiningLaser.addPreferredOre(5, <minecraft:fish>);
MiningLaser.addPreferredOre(9, <appliedenergistics2:tile.OreQuartz>);

<MineFactoryReloaded:laserfocus:0>.displayName = "Clear Focus";
<MineFactoryReloaded:laserfocus:0>.addTooltip("Increases the chance of finding");
<MineFactoryReloaded:laserfocus:0>.addTooltip("Salt and Nether Quartz");

<MineFactoryReloaded:laserfocus:1>.displayName = "Utility Focus";
<MineFactoryReloaded:laserfocus:1>.addTooltip("Increases the chance of finding some non-");
<MineFactoryReloaded:laserfocus:1>.addTooltip("metal ores such as Zinc, Manganese, or Bitumen");

<MineFactoryReloaded:laserfocus:2>.displayName = "Hard Alien Focus";
<MineFactoryReloaded:laserfocus:2>.addTooltip("Increases the chance of finding high-grade");
<MineFactoryReloaded:laserfocus:2>.addTooltip("alien metals such as Atlarus and Adamantine");

<MineFactoryReloaded:laserfocus:3>.displayName = "Diamond Focus";
<MineFactoryReloaded:laserfocus:3>.addTooltip("Increases the chance");
<MineFactoryReloaded:laserfocus:3>.addTooltip("of finding Diamonds.");

<MineFactoryReloaded:laserfocus:4>.displayName = "Power Focus";
<MineFactoryReloaded:laserfocus:4>.addTooltip("Increases the chance of");
<MineFactoryReloaded:laserfocus:4>.addTooltip("finding Coal and Nuclear Fuel");

<MineFactoryReloaded:laserfocus:5>.displayName = "Fishy Focus";
<MineFactoryReloaded:laserfocus:5>.addTooltip("Increases the chance of");
<MineFactoryReloaded:laserfocus:5>.addTooltip("finding... fish? Probably");
<MineFactoryReloaded:laserfocus:5>.addTooltip("best not to use this.");

<MineFactoryReloaded:laserfocus:6>.displayName = "Nether Alien Focus";
<MineFactoryReloaded:laserfocus:6>.addTooltip("Increases the chance of");
<MineFactoryReloaded:laserfocus:6>.addTooltip("finding alien nether ores.");

<MineFactoryReloaded:laserfocus:7>.displayName = "Iron Focus";
<MineFactoryReloaded:laserfocus:7>.addTooltip("Increases the chance of finding");
<MineFactoryReloaded:laserfocus:7>.addTooltip("Iron and its alien variants.");

<MineFactoryReloaded:laserfocus:8>.displayName = "Tech Focus";
<MineFactoryReloaded:laserfocus:8>.addTooltip("Increases the chance of");
<MineFactoryReloaded:laserfocus:8>.addTooltip("finding the six tech metals.");

<MineFactoryReloaded:laserfocus:9>.displayName = "Certus Focus";
<MineFactoryReloaded:laserfocus:9>.addTooltip("Increases the chance of");
<MineFactoryReloaded:laserfocus:9>.addTooltip("finding Certus Quartz.");

<MineFactoryReloaded:laserfocus:10>.displayName = "Shard Focus";
<MineFactoryReloaded:laserfocus:10>.addTooltip("Increases the chance of");
<MineFactoryReloaded:laserfocus:10>.addTooltip("finding Infused Stone.");

<MineFactoryReloaded:laserfocus:11>.displayName = "Lapis Focus";
<MineFactoryReloaded:laserfocus:11>.addTooltip("Increases the chance");
<MineFactoryReloaded:laserfocus:11>.addTooltip("of finding Lapis.");

<MineFactoryReloaded:laserfocus:12>.displayName = "Soft Alien Focus";
<MineFactoryReloaded:laserfocus:12>.addTooltip("Increases the chance of finding low-grade");
<MineFactoryReloaded:laserfocus:12>.addTooltip("alien metals like Prometheum and Oureclase.");

<MineFactoryReloaded:laserfocus:13>.displayName = "Emerald Focus";
<MineFactoryReloaded:laserfocus:13>.addTooltip("Increases the chance");
<MineFactoryReloaded:laserfocus:13>.addTooltip("of finding Emeralds.");

<MineFactoryReloaded:laserfocus:14>.displayName = "Nether Focus";
<MineFactoryReloaded:laserfocus:14>.addTooltip("Increases the chance of finding");
<MineFactoryReloaded:laserfocus:14>.addTooltip("nether variants of most ores.");

<MineFactoryReloaded:laserfocus:15>.displayName = "End Focus";
<MineFactoryReloaded:laserfocus:15>.addTooltip("Increases the chance of");
<MineFactoryReloaded:laserfocus:15>.addTooltip("finding alien ender metals");

furnace.addRecipe(<customnpcs:npcSaphire> *2, <ore:oreNetherSapphire>, 0.5);
mods.thermalexpansion.Pulverizer.addRecipe(3200, <NetherOres:tile.netherores.ore.0:15>, <customnpcs:npcSaphire> *5, <minecraft:netherrack>, 15);
mods.thermalexpansion.Furnace.addRecipe(1600, <NetherOres:tile.netherores.ore.0:15>, <customnpcs:npcSaphire> *2);
mods.thermalexpansion.Smelter.addRecipe(3200, <NetherOres:tile.netherores.ore.0:15>, <minecraft:sand>, <customnpcs:npcSaphire>*2, <ThermalExpansion:material:515>, 10);
mods.thermalexpansion.Smelter.addRecipe(7200, <NetherOres:tile.netherores.ore.0:15>, <ThermalExpansion:material:515>, <customnpcs:npcSaphire>*3, <ThermalExpansion:material:514>, 100);

furnace.addRecipe(<ExtraTiC:chunk:165> *2, <ore:oreNetherPeridot>, 0.5);
mods.thermalexpansion.Pulverizer.addRecipe(3200, <NetherOres:tile.netherores.ore.0:14>, <ExtraTiC:chunk:165> *5, <minecraft:netherrack>, 15);
mods.thermalexpansion.Furnace.addRecipe(1600, <NetherOres:tile.netherores.ore.0:14>, <ExtraTiC:chunk:165> *2);
mods.thermalexpansion.Smelter.addRecipe(3200, <NetherOres:tile.netherores.ore.0:14>, <minecraft:sand>, <ExtraTiC:chunk:165>*2, <ThermalExpansion:material:515>, 10);
mods.thermalexpansion.Smelter.addRecipe(7200, <NetherOres:tile.netherores.ore.0:14>, <ThermalExpansion:material:515>, <ExtraTiC:chunk:165>*3, <ThermalExpansion:material:514>, 100);
